---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-mariadb-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-mariadb
      component: mariadb
      schema: armada/Chart/v1
    actions:
      - method: delete
        path: .values.labels.prometheus_mysql_exporter
  storagePolicy: cleartext
data: {}
...
