---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-heat-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-heat
      component: heat
    actions:
      - method: merge
        path: .sequenced
      - method: replace
        path: .chart_group
  storagePolicy: cleartext
data:
  sequenced: true
  chart_group:
    - heat-rabbitmq-airskiff
    - heat
