---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: heat-rabbitmq-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: heat-rabbitmq
      component: heat
    actions:
      - method: delete
        path: .values.labels.prometheus_rabbitmq_exporter
      - method: replace
        path: .values.monitoring
  storagePolicy: cleartext
data:
  values:
    monitoring:
      prometheus:
        enabled: false
...
