---
# NOTE(@drewwalters96): This file is a duplicate of the airship-seaworthy site
#   and is not used by Airskiff.
schema: shipyard/DeploymentConfiguration/v1
metadata:
  schema: metadata/Document/v1
  name: deployment-configuration
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  armada:
    manifest: full-site
...
