---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-controller-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-ingress-controller-global
      component: ingress
      type: group
    actions:
      - method: replace
        path: .chart_group
  storagePolicy: cleartext
data:
  chart_group:
    - openstack-ingress-controller-airskiff
...
