schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: nova-global
      component: nova
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      ceph:
        enabled: false
...
