---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-controller
  labels:
    name: openstack-ingress-controller-global
    component: ingress
    type: group
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: OpenStack Namespace Ingress
  chart_group:
    - openstack-ingress-controller
